### ISSUE TITLE
Symbol's value as variable is void: compilation-error-regexp-alist-alist

### ISSUE THREAD

**Issue by dakrone** [aredington/kibit-mode#1]
Using Emacs 24, clojure-mode 1.11.5 (from git) and the latest kibit-mode.

Here's what I have in my init.el:

``` lisp
(add-to-list 'load-path "~/src/clj/kibit-mode")
(require 'kibit-mode)
(add-hook 'clojure-mode-hook 'kibit-mode)
```

I get

`Symbol's value as variable is void: compilation-error-regexp-alist-alist`

When opening a Clojure file in emacs.

**Comment by aredington** [comment]
I neglected to (require 'compile) in kibit-mode.el

The latest from head includes this require. 

To test locally without updating, you could also change

```
(add-to-list 'load-path "~/src/clj/kibit-mode")
(require 'kibit-mode)
(add-hook 'clojure-mode-hook 'kibit-mode)
```

to

```
(add-to-list 'load-path "~/src/clj/kibit-mode")
(require 'compile)
(require 'kibit-mode)
(add-hook 'clojure-mode-hook 'kibit-mode)
```

And see if that resolves it. Thanks for the bug report!

**Comment by dakrone** [comment]
That does the trick, thanks!
