### ISSUE TITLE
Invalid command executable error

### ISSUE THREAD

**Issue by roryk** [aredington/kibit-mode#6]
I installed via MELPA and receive this error when I try to enable kibit-mode in a .clj buffer:

```
Invalid command executable (eval (concat kibit-mode-path "bin/kibit-flymake.sh"))
```

It evals to:

```
"/Users/rory/.emacs.d/elpa/kibit-mode-20131108.1341/bin/kibit-flymake.sh"
```

Which exists and is executable. 

If I manually run kibit-mode on a test file it works:

```
lein run -m kibit-mode.flymake bin/test.clj
bin/test.clj:1: ERROR: (if (even? x) x nil) CORRECTION: (when (even? x) x)
```

I think it is not working right with flycheck-mode, since that is where that error pops up. Do you have any suggestions? Thanks!

**Comment by aredington** [comment]
Please give the latest code reflecting bsuh's patch a try and let us know if it's resolve the issue for you.
